### ISSUE TITLE
Correlate event handlers

### ISSUE THREAD

**Issue by akashlal** [p-org/PSharp#205] opened 2017-06-30 11:38 UTC
Shaz: For debugging purposes, the Batch team wants to be able to correlate event handlers.  Any external event pumped into the P# runtime will have an id associated with it. Now, the job  of the P# runtime is to propagate this id as follows:
1.	when the event is dequeued and handled by a handler,  the id in the event should be stashed in some per-machine storage.
2.	if the handler sends an event, the current id associated with its machine should be attached to the event being sent.
Given that the plumbing in 1 and 2 is performed automatically, any call to BatchLogger in the new pool server can put the current id of the machine handler executing the log command in the log message.

The id should be a Guid.  One way to pull this off is to add a Guid-valued field to the base Event and Machine classes.  But the P# developers probably know best.  Perhaps there is something more generic that can be done.

**Comment by shazqadeer** [comment] 2017-07-14 22:33
@akashlal : Any ETA on this issue?

**Comment by akashlal** [comment] 2017-07-15 03:08
@pdeligia: Did you get started on this?
Otherwise I can take a look, early next week.

**Comment by pdeligia** [comment] 2017-07-15 07:10
Hi Akash, check the latest [commit](https://github.com/p-org/PSharp/commit/aaf87c871b96fbc875aa449910350ac9a1b86dc7), I changed the operation group ids to be GUIDs.

**Comment by pdeligia** [comment] 2017-07-16 08:59
Getters provided in ce6480c6c308be5a5234ebd95df463c5860f5051. This feature only works for testing (in production all ids are `Guid.Empty`).

**Comment by akashlal** [comment] 2017-07-17 08:11
Done with this feature. @shazqadeer

**Comment by shazqadeer** [comment] 2017-07-17 15:22
I am puzzled by pdeligia's comment: 

This feature only works for testing (in production all ids are Guid.Empty).

The feature is needed in production by the Batch team.

**Comment by pdeligia** [comment] 2017-07-17 20:37
@shazqadeer we were not sure if this feature was intended for testing or production. Its currently only enabled for testing (its no-op in production). But this could easily change (mainly need to do the same logic we do in `BugFindingRuntime` in `StateMachineRuntime`. @akashlal I can do this change later this week, unless you want to give it a go?

**Comment by akashlal** [comment] 2017-07-18 10:21
I'll do it.

**Comment by akashlal** [comment] 2017-07-19 05:53
Created pull request #222

**Comment by pdeligia** [comment] 2017-07-19 19:42
Merged #222.

**Closed by pdeligia** 2017-07-19 19:42 UTC
